services:
  processo-ocr:
    build: .
    container_name: processo_ocr_integrado
    ports:
      - "8501:8501"
      - "8080:8080"
    volumes:
      - ./app:/app
    env_file:
      - .env
    working_dir: /app
    command: streamlit run interface.py --server.headless=true --server.address=0.0.0.0 --server.port=8501
    depends_on:
      chroma:
        condition: service_healthy
    environment:
      - CHROMA_HOST=chroma
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - STREAMLIT_SERVER_HEADLESS=true
      - GOOGLE_APPLICATION_CREDENTIALS=/app/chaves-google.json

  chroma:
    image: ghcr.io/chroma-core/chroma:0.5.0
    container_name: chroma_db
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 15s
    environment:
      - ALLOW_RESET=true

volumes:
  chroma_data: